name: Build

on:
  push:
    tags:
      - "v*"

env:
  BUILD_TYPE: Release

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.ACTIONS_TOKEN }}"
        prerelease: false
        files: |
          **/libooz.so
          **/libooz.a

  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      #- name: Set up MinGW
      #  uses: egor-tensin/setup-mingw@v2
      #  with:
      #    platform: x64

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Rename
        run: |
          mv ${{github.workspace}}/build/libooz.a ${{github.workspace}}/build/libooz-win.a
          mv ${{github.workspace}}/build/libooz.dll ${{github.workspace}}/build/libooz-win.dll
      
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ACTIONS_TOKEN }}
          file_glob: true
          file: "**/libooz-win.a"
          tag: ${{ github.ref }}

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ACTIONS_TOKEN }}
          file_glob: true
          file: "**/libooz-win.dll"
          tag: ${{ github.ref }}
