name: Build

on:
  push:
    tags:
      - "v*"

env:
  BUILD_TYPE: Release

jobs:
  linux-static-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Alpine
      uses: jirutka/setup-alpine@v1
      with:
        branch: v3.17

    - name: Install dependencies
      run: apk add build-base cmake
      shell: alpine.sh --root {0}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      shell: alpine.sh {0}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      shell: alpine.sh {0}

    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.ACTIONS_TOKEN }}
        file_glob: true
        file: "**/libooz.a"
        tag: ${{ github.ref }}

  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.ACTIONS_TOKEN }}"
        prerelease: false
        files: |
          **/libooz.so
          **/ooz.h

  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ACTIONS_TOKEN }}
          file_glob: true
          file: "**/ooz.lib"
          tag: ${{ github.ref }}

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ACTIONS_TOKEN }}
          file_glob: true
          file: "**/ooz.dll"
          tag: ${{ github.ref }}
